// src/components/common/input.jsx
import styled from 'styled-components';

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
`;

const Label = styled.label`
  margin-bottom: .5rem;
`;

const TextInput = styled.input`
  border: none;
  background-color: #313638;
  padding: .75rem 1.5rem;
  outline: none;
  border-radius: .5rem;
`;

const Input = ({ label, value, onChangeValue, placeholder }) => {
  return (
    <Wrapper>
      <Label>{label}</Label>
      <TextInput value={value} onChange={onChangeValue} placeholder={placeholder}/>
    </Wrapper>
  );
}

export default Input;

// src/lib/components/form/input.svelte
<script lang="ts">
  export let
    label: string, 
    value: string,
    placeholder: string;
</script>

<div>
  <label for="">{label}</label>
  <input type="text" bind:value {placeholder} on:keyup>
</div>

<style lang="sass">
  @import '../../../vars'

  div
    display: flex
    flex-direction: column

    label
      margin-bottom: 0.5rem
      font-size: 1.25rem

    input
      padding: 1rem
      font-size: 1rem
      border-radius: 0.5rem
      background-color: $darker
      border: none
      outline: none
      transition: all .2s ease

      &:focus
        box-shadow: 0 0 0 2px $primary

  @media screen and (max-width: 768px)
    div label
      font-size: 1rem
</style>
