// src/lib/themes.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { Theme } from '../interfaces';
  import { theme as selected, ratio } from '../stores';

  let themes: Theme[] = [];
  onMount(async () => {
    themes = await(await fetch('/api/themes')).json();
  });

  const updateTheme = () => {
    if (!$selected) return;

    const theme = themes.find(x => x.slug == $selected);
    if (!theme) return;

    if (!theme?.ratios.includes($ratio)) $selected = ''; // FIXME:
  }

  $: $ratio, updateTheme();
</script>

<div
  class="themes"
  class:square={$ratio == '1by1'}
  class:vertical={$ratio == '9by16'}
  class:horizontal={$ratio == '16by9'}
>
  <label for="">Escolha um tema:</label>
  <div class="slider">
    {#each themes as theme}
      {#if theme.ratios.includes($ratio)}
        <div class="slide">
          <div
            class="theme"
            on:click={() => $selected = theme.slug}
            class:active={$selected == theme.slug}
          >
            <img src="/img/demos/{theme.slug}-{$ratio}.webp" alt="">
            <span>{theme.name}</span>
          </div>
        </div>
      {/if}
    {/each}
  </div>
</div>

<style lang="sass">
  @import '../vars'

  .themes
    display: flex
    flex-direction: column

    label
      margin-bottom: 0.5rem
      font-size: 1.25rem

    .slider
      display: flex
      width: 100%
      overflow-x: auto
      transition: height .2s ease
      padding-bottom: .5rem

      &::-webkit-scrollbar
        height: .25rem

      &::-webkit-scrollbar-track
        background: $darker

      &::-webkit-scrollbar-thumb
        background: $primary

      .slide
        flex-shrink: 0
        width: calc(25% - 1rem)

        &:not(:last-child)
          margin-right: 1rem

    .theme
      position: relative
      display: flex
      flex-direction: column
      align-items: center
      height: 100%
      background-color: $darker
      border-radius: .5rem
      cursor: pointer
      overflow: hidden

      &::before
        position: absolute
        content: ''
        height: 100%
        width: 100%
        border-radius: .5rem
        pointer-events: none
        transition: all .2s ease

      &.active::before
        box-shadow: inset 0 0 0 2px $primary

      span
        display: flex
        align-items: center
        flex-grow: 1

    &.square .slider
      height: 14.5rem

    &.vertical .slider
      height: 23.5rem

    &.horizontal .slider
      height: 9.5rem

  @media screen and (max-width: 768px)
    div
      label
        font-size: 1rem

      .slider .slide
        width: calc(50% - 1rem) !important 

      &.square .slider
        height: 13.5rem !important

      &.vertical .slider
        height: 22rem !important

      &.horizontal .slider
        height: 9rem !important
</style>

// src/components/common/themes.jsx
import styled from 'styled-components';

const Title = styled.h1`
  margin-bottom: .5rem;
`;

const List = styled.ul`
  display: flex;
  
  li {
    display: flex;
    justify-content: center;
    align-items: flex-end;
    width: 8rem;
    aspect-ratio: 9/16;
    background-color: #313638;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    border-radius: .5rem;
    cursor: pointer;
    overflow: hidden;
    transition: all .2s ease;
  }

  li h1 {
    display: flex;
    justify-content: center;
    align-items: flex-end;
    height: 4rem;
    width: 100%;
    padding: 1rem 0;
    text-align: center;
    background-image: linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, .75));
    transition: all .3s ease;
  }

  li:not(:hover) h1 {
    opacity: 0;
    transform: translateY(.5rem);
  }

  li:not(:last-child) {
    margin-right: 1rem;
  }

  li.active {
    box-shadow: 0 0 0 2px #EB459E;
  }

  @media screen and (max-width: 768px) {
    li {
      flex-shrink: 0;
    }
  }
`;

const ComingSoon = styled.ul`
  position: relative;
  display: flex;
  opacity: .5;
  pointer-events: none;

  h1 {
    position: absolute;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
    width: 100%;
    z-index: 1;
  }

  li:nth-child(3) {
    opacity: .5;
  }

  li:nth-child(4) {
    opacity: .25;
  }

  @media screen and (max-width: 768px) {
    flex-grow: 1;
    overflow: hidden;
  }
`;

const importAllImages = r => {
  const images = {};
  r.keys().forEach(item => images[item.replace('./', '')] = r(item).default);
  return images;
};
const images = importAllImages(require.context('../../assets/img', false, /\.webp$/));

const Themes = ({ themes, theme, setTheme }) => {
  const renderThemeItem = (item, index) => (
    <li 
      key={index}
      className={theme === item ? 'active' : ''}
      onClick={() => setTheme(item)}
      style={{ backgroundImage: `url('${images[`theme-${item}.webp`]}')` }}
    >
      <h1>{item}</h1>
    </li>
  );
  
  return (
    <>
      <Title>Agora escolha um tema:</Title>
      <List>
        {themes.map((item, index) => renderThemeItem(item, index))}
        <ComingSoon>
          <h1>Mais temas em breve...</h1>
          <li></li>
          <li></li>
          <li></li>
        </ComingSoon>
      </List>
    </>
  );
}

export default Themes;
